# Generated by Django 2.0.7 on 2018-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inn',
            field=models.BigIntegerField(),
            preserve_default=False,
        ),
    ]
