# Generated by Django 2.0.7 on 2018-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='inn',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
